#!/usr/bin/env bash
# Inspired by henrik's Rakefile at https://github.com/henrik/dotfiles/blob/master/Rakefile

while getopts "sv" flag; do
  case "${flag}" in
    s) SIM=1;;
    v) BVE=1;;
  esac
done

IGNORE_FILES=(
  ".gitignore"
  "LICENSE"
  "README.md"
  "$(basename "$0")"  # or just "dots"
)

DOT_PATH=$(dirname "$(readlink -f "$0")")
[ $BVE ] && echo "DOT_PATH: $DOT_PATH"
[ $BVE ] && [ $SIM ] && echo "**** This is a simulation! ****"

for DOT_FILE in $DOT_PATH/*; do
  DOT_FILE=$(basename "${DOT_FILE}")
  
  if [[ ! "${IGNORE_FILES[@]}" =~ "${DOT_FILE}" ]]; then
    [ $BVE ] && echo ".$DOT_FILE"
  
    # If the link is already a link and not pointing to DOT_PATH
    if [ -L "$HOME/.$DOT_FILE" ]; then
      [ $BVE ] || [ $SIM ] && echo " - unlinked from $(readlink -f $HOME/.$DOT_FILE)"
      #[ ! $SIM ] && rm "$HOME/.$DOT_FILE"
    fi
    
    # If the link is a regular file
    if [ -f $HOME/.$DOT_FILE ]; then
      [ $BVE ] || [ $SIM ] && echo " - renamed to $HOME/$DOT_FILE.dots"
      #[ ! $SIM ] && mv -f "$HOME/.$DOT_FILE" "$HOME/$DOT_FILE.dots"
    fi
    
    # Create the link
    [ $BVE ] || [ $SIM ] && echo " - linked to $DOT_PATH/$DOT_FILE"
    #[ ! $SIM ] && ln -s "$DOT_PATH/$DOT_FILE" "$HOME/.$DOT_FILE"
  fi
done

# Check for files named *.dots (e.g. bash_aliases.dots)
if [ "$(ls -al $HOME/*.dots 2> /dev/null | wc -l)" != "0" ]; then
  echo "The following files may have been created by this script and could be removed:"
  ls -al *.dots
fi
